import React, { useState, useEffect } from 'react';
import MarkdownRenderer from './MarkdownRenderer';
import { Copy, Check, Download, AlertCircle, Sparkles, BarChart3, Clock, ChevronRight, History, LayoutTemplate, Info, FileText, FileCode, FileType, ChevronDown } from 'lucide-react';
import { GeneratedPRD } from '../types';

interface OutputDisplayProps {
  data: GeneratedPRD | null;
  error: string | null;
  isGenerating: boolean;
  history: GeneratedPRD[];
  onSelectVersion: (prd: GeneratedPRD) => void;
}

const OutputDisplay: React.FC<OutputDisplayProps> = ({ 
  data, 
  error, 
  isGenerating, 
  history, 
  onSelectVersion 
}) => {
  const [copied, setCopied] = useState(false);
  const [showHistory, setShowHistory] = useState(false);
  const [showExportMenu, setShowExportMenu] = useState(false);
  const [loadingStep, setLoadingStep] = useState(0);

  const loadingMessages = [
    "Analyzing project requirements...",
    "Defining core user personas...",
    "Structuring technical specifications...",
    "Drafting detailed user stories...",
    "Polishing document format..."
  ];

  useEffect(() => {
    let interval: ReturnType<typeof setInterval>;
    if (isGenerating) {
      setLoadingStep(0);
      interval = setInterval(() => {
        setLoadingStep((prev) => (prev + 1) % loadingMessages.length);
      }, 2000);
    }
    return () => clearInterval(interval);
  }, [isGenerating]);

  const handleCopy = () => {
    if (data?.markdownContent) {
      navigator.clipboard.writeText(data.markdownContent);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleExportMD = () => {
    if (data?.markdownContent) {
      const element = document.createElement("a");
      const file = new Blob([data.markdownContent], {type: 'text/plain'});
      element.href = URL.createObjectURL(file);
      element.download = `${data.title.replace(/\s+/g, '_')}_PRD.md`;
      document.body.appendChild(element); 
      element.click();
      document.body.removeChild(element);
    }
  };

  const handleExportPDF = () => {
    if (!data) return;
    const printWindow = window.open('', '', 'width=800,height=600');
    if (printWindow) {
        const content = document.querySelector('.markdown-body')?.innerHTML || '';
        printWindow.document.write(`
            <html>
                <head>
                    <title>${data.title} - PRD</title>
                    <style>
                        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; padding: 40px; line-height: 1.6; color: #333; max-width: 800px; mx-auto; }
                        h1 { font-size: 24pt; border-bottom: 2px solid #eee; padding-bottom: 10px; margin-bottom: 24px; color: #111; }
                        h2 { font-size: 18pt; margin-top: 24px; margin-bottom: 12px; color: #333; border-bottom: 1px solid #f0f0f0; padding-bottom: 6px; }
                        h3 { font-size: 14pt; margin-top: 20px; margin-bottom: 10px; color: #444; }
                        p { margin-bottom: 12px; text-align: justify; }
                        ul, ol { margin-bottom: 16px; padding-left: 24px; }
                        li { margin-bottom: 6px; }
                        table { border-collapse: collapse; width: 100%; margin-bottom: 24px; font-size: 10pt; }
                        th, td { border: 1px solid #ddd; padding: 8px 12px; text-align: left; }
                        th { background-color: #f8f9fa; font-weight: bold; }
                        code { background-color: #f5f5f5; padding: 2px 5px; border-radius: 3px; font-family: monospace; font-size: 0.9em; }
                        pre { background-color: #f8f8f8; padding: 16px; border-radius: 8px; overflow-x: auto; margin-bottom: 20px; border: 1px solid #eee; }
                        blockquote { border-left: 4px solid #ddd; margin: 0; padding-left: 16px; color: #666; font-style: italic; }
                    </style>
                </head>
                <body>
                    <h1>${data.title}</h1>
                    <div style="margin-bottom: 30px; font-size: 10pt; color: #666;">Generated by ProPRD • ${new Date().toLocaleDateString()}</div>
                    ${content}
                    <script>
                        window.onload = function() { window.print(); window.close(); }
                    </script>
                </body>
            </html>
        `);
        printWindow.document.close();
    }
  };

  const handleExportWord = () => {
    if (!data) return;
    const preHtml = "<html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'><head><meta charset='utf-8'><title>Export HTML to Word Document with JavaScript</title></head><body>";
    const postHtml = "</body></html>";
    const content = document.querySelector('.markdown-body')?.innerHTML || '';
    
    // Add inline styles for the Word document to ensure table borders etc show up
    const styledContent = `
        <style>
            body { font-family: 'Calibri', sans-serif; }
            table { border-collapse: collapse; width: 100%; }
            td, th { border: 1px solid #000; padding: 8px; }
            h1 { font-size: 24pt; color: #111; }
            h2 { font-size: 18pt; color: #333; }
        </style>
        <h1>${data.title}</h1>
        ${content}
    `;

    const html = preHtml + styledContent + postHtml;

    const blob = new Blob(['\ufeff', html], {
        type: 'application/msword'
    });
    
    const url = 'data:application/vnd.ms-word;charset=utf-8,' + encodeURIComponent(html);
    
    const downloadLink = document.createElement("a");
    document.body.appendChild(downloadLink);
    
    if (navigator.userAgent.indexOf("Safari") !== -1 && navigator.userAgent.indexOf("Chrome") === -1) {
        // Safari fallback
        downloadLink.setAttribute("target", "_blank");
        downloadLink.href = url;
    } else {
        downloadLink.href = URL.createObjectURL(blob);
    }
    
    downloadLink.download = `${data.title.replace(/\s+/g, '_')}.doc`;
    downloadLink.click();
    document.body.removeChild(downloadLink);
  };

  const getScoreColor = (score: number) => {
    if (score >= 90) return 'text-emerald-700 bg-emerald-50 ring-emerald-500/20';
    if (score >= 75) return 'text-teal-700 bg-teal-50 ring-teal-500/20';
    if (score >= 60) return 'text-amber-700 bg-amber-50 ring-amber-500/20';
    return 'text-rose-700 bg-rose-50 ring-rose-500/20';
  };

  const formatDate = (timestamp: number) => {
    return new Date(timestamp).toLocaleString('en-US', {
      month: 'short',
      day: 'numeric',
      hour: 'numeric',
      minute: '2-digit'
    });
  };

  const scoreClass = data ? getScoreColor(data.completenessScore) : '';

  // Render Content Logic
  const renderContent = () => {
    if (isGenerating) {
      return (
        <div className="h-full flex flex-col items-center justify-center p-12 bg-zinc-50/50">
           <div className="bg-white p-8 rounded-2xl shadow-2xl shadow-zinc-200/50 border border-zinc-100 flex flex-col items-center text-center max-w-sm mx-auto relative overflow-hidden transition-all duration-300">
              {/* Top accent line */}
              <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-rose-400 via-amber-400 to-emerald-400"></div>

              <div className="w-16 h-16 bg-zinc-50 rounded-2xl mb-6 flex items-center justify-center relative shadow-inner">
                 <Sparkles className="w-8 h-8 text-indigo-500 animate-pulse" />
              </div>
              
              <h3 className="text-xl font-bold text-zinc-900 mb-2 tracking-tight">Constructing PRD</h3>
              
              <p className="text-zinc-500 text-sm mb-8 h-6 transition-all duration-300 font-medium">
                {loadingMessages[loadingStep]}
              </p>

              {/* Progress Bar Container */}
              <div className="w-full h-1.5 bg-zinc-100 rounded-full overflow-hidden relative">
                 {/* Animated Bar */}
                 <div className="absolute top-0 left-0 h-full w-full bg-gradient-to-r from-transparent via-indigo-600 to-transparent animate-indeterminate rounded-full shadow-[0_0_12px_rgba(79,70,229,0.5)]"></div>
              </div>
           </div>
        </div>
      );
    }

    if (error) {
      return (
        <div className="h-full flex flex-col items-center justify-center p-8">
          <div className="bg-white p-8 rounded-2xl shadow-lg border border-red-100 text-center max-w-md">
            <div className="bg-rose-50 w-12 h-12 rounded-full flex items-center justify-center mx-auto mb-4">
              <AlertCircle className="w-6 h-6 text-rose-500" />
            </div>
            <h3 className="text-lg font-bold text-zinc-900 mb-2">Generation Failed</h3>
            <p className="text-zinc-500 text-sm">{error}</p>
          </div>
        </div>
      );
    }

    if (!data) {
      return (
        <div className="h-full flex flex-col items-center justify-center p-12 text-center opacity-60">
          <div className="w-24 h-24 bg-white rounded-3xl shadow-sm border border-zinc-200 flex items-center justify-center mb-6 transform rotate-3 transition-transform hover:rotate-6 duration-500">
            <LayoutTemplate className="w-10 h-10 text-zinc-300" />
          </div>
          <h3 className="text-xl font-bold text-zinc-900 mb-2 tracking-tight">Your Workspace is Empty</h3>
          <p className="text-zinc-500 max-w-sm mx-auto leading-relaxed">
            Use the panel on the left to define your project. The AI will generate a structured PRD document here.
          </p>
        </div>
      );
    }

    return (
      <div className="w-full max-w-4xl mx-auto px-6 py-8 pb-32">
        {/* Analysis Card */}
        <div className="mb-6 bg-white rounded-xl p-5 border border-zinc-200 shadow-sm flex items-start gap-4 hover:shadow-md transition-shadow">
          <div className="mt-1 p-2 bg-indigo-50 rounded-lg border border-indigo-100">
            <BarChart3 className="w-5 h-5 text-indigo-600" />
          </div>
          <div>
            <h4 className="text-sm font-bold text-zinc-900 mb-1 flex items-center gap-2">
              AI Analysis
              <div className="group relative flex items-center">
                <span className={`text-[10px] px-2 py-0.5 rounded-full font-bold ring-1 ${scoreClass} flex items-center gap-1.5 cursor-help transition-all hover:ring-2`}>
                  Quality Score: {data.completenessScore}/100
                  <Info className="w-3 h-3 opacity-70" />
                </span>
                
                {/* Tooltip */}
                <div className="absolute left-1/2 -translate-x-1/2 bottom-full mb-2 w-64 p-3 bg-zinc-900 text-white text-xs rounded-lg shadow-xl opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all duration-200 z-50 pointer-events-none text-center font-normal leading-relaxed">
                    Calculated based on clarity, completeness, feature feasibility, and alignment with professional PRD standards.
                    <div className="absolute -bottom-1 left-1/2 -translate-x-1/2 w-2 h-2 bg-zinc-900 rotate-45"></div>
                </div>
              </div>
            </h4>
            <p className="text-sm text-zinc-600 leading-relaxed">
              {data.qualityAnalysis}
            </p>
          </div>
        </div>

        {/* The Document "Sheet" */}
        <div className="bg-white shadow-[0_8px_30px_rgb(0,0,0,0.04)] border border-zinc-200 rounded-xl min-h-[800px] overflow-hidden">
            {/* Fake Document Header */}
            <div className="h-14 border-b border-zinc-100 flex items-center px-8 bg-zinc-50/30">
                <div className="flex space-x-2">
                    <div className="w-3 h-3 rounded-full bg-rose-400/20 border border-rose-400/30"></div>
                    <div className="w-3 h-3 rounded-full bg-amber-400/20 border border-amber-400/30"></div>
                    <div className="w-3 h-3 rounded-full bg-emerald-400/20 border border-emerald-400/30"></div>
                </div>
                <div className="ml-auto text-xs text-zinc-400 font-medium uppercase tracking-wider">
                    Markdown Preview
                </div>
            </div>
            
            <div className="p-10 md:p-14">
                <h1 className="text-4xl font-extrabold text-zinc-900 tracking-tight mb-2">{data.title}</h1>
                <p className="text-zinc-400 text-sm mb-10 font-medium flex items-center">
                    Generated on {formatDate(data.timestamp)}
                    <span className="mx-2 text-zinc-300">•</span>
                    ProPRD v1.0
                </p>
                <MarkdownRenderer content={data.markdownContent} />
            </div>
        </div>
      </div>
    );
  };

  return (
    <div className="flex flex-col h-full relative">
      {/* Toolbar */}
      <div className="flex items-center justify-between px-6 py-3 border-b border-zinc-200 bg-white z-20 sticky top-0 shadow-[0_2px_10px_-4px_rgba(0,0,0,0.05)]">
        <div className="flex items-center space-x-4">
           {/* Left side toolbar items (maybe breadcrumbs later) */}
           <span className="text-xs font-semibold text-zinc-400 uppercase tracking-widest">Workspace</span>
        </div>
        
        <div className="flex items-center space-x-2">
          {history.length > 0 && (
            <button
              onClick={() => setShowHistory(!showHistory)}
              className={`flex items-center px-3 py-1.5 text-xs font-medium rounded-lg transition-colors border ${
                showHistory 
                  ? 'bg-zinc-100 text-zinc-900 border-zinc-200' 
                  : 'bg-white text-zinc-600 border-transparent hover:bg-zinc-50 hover:border-zinc-200'
              }`}
            >
              <History className="w-4 h-4 mr-2" />
              History
            </button>
          )}

          {data && !isGenerating && !error && (
            <>
              <div className="w-px h-4 bg-zinc-200 mx-1"></div>
              
              <button
                onClick={handleCopy}
                className="flex items-center px-3 py-1.5 text-xs font-medium text-zinc-700 bg-white border border-zinc-200 rounded-lg hover:bg-zinc-50 transition-all active:scale-95"
              >
                {copied ? <Check className="w-3.5 h-3.5 mr-2 text-emerald-600" /> : <Copy className="w-3.5 h-3.5 mr-2" />}
                {copied ? 'Copied' : 'Copy'}
              </button>

              <div className="relative">
                <button
                  onClick={() => setShowExportMenu(!showExportMenu)}
                  className="flex items-center px-3 py-1.5 text-xs font-medium text-white bg-zinc-900 border border-zinc-900 rounded-lg hover:bg-zinc-800 transition-all shadow-sm active:scale-95"
                >
                  <Download className="w-3.5 h-3.5 mr-2" />
                  Export
                  <ChevronDown className="w-3 h-3 ml-1.5 opacity-70" />
                </button>
                
                {showExportMenu && (
                  <>
                    <div className="fixed inset-0 z-10" onClick={() => setShowExportMenu(false)}></div>
                    <div className="absolute right-0 mt-2 w-48 bg-white rounded-xl shadow-xl border border-zinc-100 ring-1 ring-black/5 z-20 py-1 overflow-hidden animate-in fade-in zoom-in-95 duration-200 origin-top-right">
                       <button onClick={() => { handleExportMD(); setShowExportMenu(false); }} className="w-full text-left px-4 py-2.5 text-xs text-zinc-700 hover:bg-zinc-50 flex items-center gap-3 transition-colors">
                          <FileCode className="w-4 h-4 text-zinc-400" />
                          Markdown (.md)
                       </button>
                       <button onClick={() => { handleExportPDF(); setShowExportMenu(false); }} className="w-full text-left px-4 py-2.5 text-xs text-zinc-700 hover:bg-zinc-50 flex items-center gap-3 transition-colors">
                          <FileType className="w-4 h-4 text-rose-500" />
                          PDF Document
                       </button>
                       <button onClick={() => { handleExportWord(); setShowExportMenu(false); }} className="w-full text-left px-4 py-2.5 text-xs text-zinc-700 hover:bg-zinc-50 flex items-center gap-3 transition-colors">
                          <FileText className="w-4 h-4 text-blue-600" />
                          Word File (.doc)
                       </button>
                    </div>
                  </>
                )}
              </div>
            </>
          )}
        </div>
      </div>
      
      {/* Scrollable Canvas */}
      <div className="flex-1 overflow-y-auto custom-scrollbar relative">
        {renderContent()}
      </div>

      {/* History Drawer */}
      <div 
        className={`absolute top-0 right-0 bottom-0 w-80 bg-white border-l border-zinc-200 shadow-2xl transform transition-transform duration-300 ease-in-out z-30 flex flex-col ${
          showHistory ? 'translate-x-0' : 'translate-x-full'
        }`}
      >
        <div className="p-4 border-b border-zinc-100 flex justify-between items-center bg-zinc-50/80 backdrop-blur-sm">
          <h3 className="font-bold text-zinc-900 flex items-center text-sm">
            <Clock className="w-4 h-4 mr-2 text-zinc-500" />
            Version History
          </h3>
          <button 
            onClick={() => setShowHistory(false)}
            className="p-1.5 rounded-md text-zinc-400 hover:text-zinc-600 hover:bg-zinc-200/50 transition-colors"
          >
            <ChevronRight className="w-4 h-4" />
          </button>
        </div>
        <div className="flex-1 overflow-y-auto custom-scrollbar p-3 space-y-2 bg-zinc-50/30">
          {history.map((item) => (
            <div
              key={item.id}
              className={`w-full text-left p-3 rounded-xl border transition-all group relative overflow-hidden flex flex-col ${
                data?.id === item.id
                  ? 'bg-white border-zinc-900 ring-1 ring-zinc-900 shadow-sm z-10'
                  : 'bg-white border-zinc-200 hover:border-zinc-300 hover:shadow-md'
              }`}
            >
              <button 
                onClick={() => {
                  onSelectVersion(item);
                  if (window.innerWidth < 1024) setShowHistory(false);
                }}
                className="w-full text-left mb-2"
              >
                <div className="flex justify-between items-center mb-1">
                  <span className="text-[10px] text-zinc-400 font-medium">
                    {formatDate(item.timestamp)}
                  </span>
                  <span className={`text-[9px] font-bold px-1.5 py-0.5 rounded-full uppercase tracking-wider ${
                    item.completenessScore >= 80 ? 'bg-emerald-50 text-emerald-700' : 
                    item.completenessScore >= 60 ? 'bg-amber-50 text-amber-700' : 'bg-rose-50 text-rose-700'
                  }`}>
                    {item.completenessScore} Score
                  </span>
                </div>
                <h4 className={`text-sm font-bold truncate ${
                  data?.id === item.id ? 'text-zinc-900' : 'text-zinc-700 group-hover:text-zinc-900'
                }`}>
                  {item.title || "Untitled"}
                </h4>
              </button>
              
               <button
                  onClick={(e) => {
                    e.stopPropagation();
                    onSelectVersion(item); 
                    if (window.innerWidth < 1024) setShowHistory(false);
                  }}
                  className="mt-1 text-[10px] font-semibold text-indigo-600 hover:text-indigo-800 bg-indigo-50 hover:bg-indigo-100 py-1 px-2 rounded self-start transition-colors"
               >
                 Restore & View
               </button>
            </div>
          ))}
          {history.length === 0 && (
              <div className="text-center py-10 text-zinc-400 text-xs">
                  No history available.
              </div>
          )}
        </div>
      </div>
      
      {/* Overlay when history is open on mobile */}
      {showHistory && (
        <div 
            className="absolute inset-0 bg-black/20 z-20 lg:hidden backdrop-blur-sm"
            onClick={() => setShowHistory(false)}
        ></div>
      )}
    </div>
  );
};

export default OutputDisplay;